### ISSUE TITLE
when decoding，something wrong.

### ISSUE THREAD

**Issue by ljsun** [yaserkl/RLSeq2Seq#17]
hello, when I decode using eval model, something wrong, 
could you help me?
the main information is:
Traceback (most recent call last):
  File "run_summarization.py", line 845, in <module>
    tf.app.run()
  File "/home/ices/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "run_summarization.py", line 841, in main
    seq2seq.main(unused_argv)
  File "run_summarization.py", line 810, in main
    decoder.decode()  # decode indefinitely (unless single_pass=True, in which case deocde the dataset exactly once)
  File "/home/ices/zhangbowen/RLSeq2Seq/src/decode.py", line 115, in decode
    best_hyp = beam_search.run_beam_search(self._sess, self._model, self._vocab, batch)
  File "/home/ices/zhangbowen/RLSeq2Seq/src/beam_search.py", line 144, in run_beam_search
    prev_encoder_es = encoder_es if FLAGS.use_temporal_attention else tf.stack([], axis=0))
  File "/home/ices/zhangbowen/RLSeq2Seq/src/model.py", line 855, in decode_onestep
    results = sess.run(to_return, feed_dict=feed) # run the decoder step
  File "/home/ices/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/ices/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1111, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (4, 256) for Tensor 'prev_decoder_outputs:0', which has shape '(?, 4, 256)'

**Comment by yaserkl** [comment]
Could you plz share your command?

**Comment by ljsun** [comment]
**my command is blow:**
`python run_summarization.py --mode=decode --data_path=../data_no_extract/finished_files/chunked/submit_* --vocab_path=../data_no_extract/finished_files/vocab --log_root=../log --exp_name=intradecoder-temporalattention-withpretraining --rl_training=False --intradecoder=True --use_temporal_attention=True --single_pass=1 --beam_size=4 --decode_from=eval`
I just want use pretraining model to decode, so the rl_training=Flase.
But now I solve this problem by modify some code in beam_search.py. The modified code is part of following.
`# decoder_outputs = [[h.decoder_output for h in hyps]]
        decoder_outputs = np.array([h.decoder_output for h in hyps]).swapaxes(0, 1)`
`# encoder_es = [[h.encoder_mask for h in hyps]]
        encoder_es = np.array([h.encoder_mask for h in hyps]).swapaxes(0, 1)`
**Now I have trained the model by RL. But when I use the trained RL model to decode,  all decoded result is same.**
This must be wrong, but I don't now how to fix it. 
**Could you plz help me?**

**Comment by yaserkl** [comment]
For CNN/DM dataset with 287226 train size, I'd suggest the following setup:
Train this model using batch size 32 for 15 epochs (max_iter=134637)
then activate RL training for another 15 epochs (max_iter=269274) and eta=1/269274=3.71368E-06 and then coverage for 3 epochs. Then you might be able to see some results. BTW, make sure to activate scheduled sampling during RL training with scheduled_probability equal to eta.

**Comment by ljsun** [comment]
Thank you for your reply, but if I just only want to use RL training, Should i set **eta=1**, **scheduled_sampling＝True** and **sampling_probability=1**?

**Comment by ljsun** [comment]
Thank you for your reply!
But now I just want to use RL loss and no MLE loss, should i need to set **eat=1**, **scheduled_sampling=True** , and **sampling_probability=1**?

**Comment by ljsun** [comment]
Thank you for you reply!
but I just want to use RL loss and no MLE loss, should I set **eta=1**,  **scheduled_sampling=True**, **sampling_probability=1**?

**Comment by ljsun** [comment]
Thank you for your reply!
But now I just want to use RL loss and no MLE loss, should I set **eta=1**, **scheduled_sampling=True**, **sampling_probability=1**?

**Comment by yaserkl** [comment]
Yes, but this only works if you have a very well-trained model based on MLE loss and usually what researchers do is not to use eta=1 but use a value that is close to 1, i.e. eta=0.9984. Check out Paulus et. all paper for more information.

**Comment by BeckyWang** [comment]
> For CNN/DM dataset with 287226 train size, I'd suggest the following setup:
> Train this model using batch size 32 for 15 epochs (max_iter=134637)
> then activate RL training for another 15 epochs (max_iter=269274) and eta=1/269274=3.71368E-06 and then coverage for 3 epochs. Then you might be able to see some results. BTW, make sure to activate scheduled sampling during RL training with scheduled_probability equal to eta.

In the third step( coverage for 3 epochs), should I set **rl_training=True** and **eta=1/269274=3.71368E-06**at the same time？

**Comment by xiangriconglin** [comment]
> **my command is blow:**
> `python run_summarization.py --mode=decode --data_path=../data_no_extract/finished_files/chunked/submit_* --vocab_path=../data_no_extract/finished_files/vocab --log_root=../log --exp_name=intradecoder-temporalattention-withpretraining --rl_training=False --intradecoder=True --use_temporal_attention=True --single_pass=1 --beam_size=4 --decode_from=eval`
> I just want use pretraining model to decode, so the rl_training=Flase.
> But now I solve this problem by modify some code in beam_search.py. The modified code is part of following.
> `# decoder_outputs = [[h.decoder_output for h in hyps]] decoder_outputs = np.array([h.decoder_output for h in hyps]).swapaxes(0, 1)`
> `# encoder_es = [[h.encoder_mask for h in hyps]] encoder_es = np.array([h.encoder_mask for h in hyps]).swapaxes(0, 1)`
> **Now I have trained the model by RL. But when I use the trained RL model to decode, all decoded result is same.**
> This must be wrong, but I don't now how to fix it.
> **Could you plz help me?**

Excuse me, have you solved this problem?
Now i meet the same problem that all decoded result is same. My command is:
`python src/run_summarization.py --mode=train --data_path=./data/cnn_dm/chunked/train_* --vocab_path=./data/cnn_dm/vocab --log_root=./log --exp_name=pointer-generator --batch_size=16 --max_iter=600000`
Expect for your reply, thank you!

**Comment by yaserkl** [comment]
Could you please share your decoding command and some of the outputs?

**Comment by xiangriconglin** [comment]
Thank you very much. The issue has been solve. Thank you for your reply.

**Comment by DengYangyong** [comment]
> 
> 
> Thank you very much. The issue has been solve. Thank you for your reply.

I meet the sample problem that all the decoded results of different examples are the same no matter  I set rl_training=Flase or True, and I have trained the model for about 300000 steps and the loss has stopped failling.

How did you solve the issue? This is very important to me and I am looking forward to your reply.

**Comment by DengYangyong** [comment]
I meet the sample problem as you when I train the model in chinese dataset.
In addtion, the loss is too high which was 11 at the beggining and decreased to about 6 after 30K steps.
There may be same problem with the code as when I use the pytorch version ( https://github.com/rohithreddy024/Text-Summarizer-Pytorch) to train the model , the loss ranged from 6 to 0.8 and the results were good.
