### ISSUE TITLE
when convert to RL model something wrong

### ISSUE THREAD

**Issue by zhangxiaoyidog** [yaserkl/RLSeq2Seq#22]
hello,when i convert to RL model something wrong,can u help me, the mistake is:
Traceback (most recent call last):
  File "src/run_summarization.py", line 846, in <module>
    tf.app.run()
  File "/home/ices/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "src/run_summarization.py", line 842, in main
    seq2seq.main(unused_argv)
  File "src/run_summarization.py", line 792, in main
    self.setup_training()
  File "src/run_summarization.py", line 296, in setup_training
    self.model.build_graph()  # build the graph
  File "/home/ices/zhangbowen/RLSeq2Seq/src/model.py", line 514, in build_graph
    self._add_seq2seq()
  File "/home/ices/zhangbowen/RLSeq2Seq/src/model.py", line 312, in _add_seq2seq
    tf.unstack(self.sampling_rewards)))  # list of max_dec_steps * (batch_size, k)
  File "/home/ices/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1091, in unstack
    raise ValueError("Cannot infer num from shape %s" % value_shape)
ValueError: Cannot infer num from shape (?, 1)

**Comment by yaserkl** [comment]
Have you updated the code with recent changes?
Also, if the error persists with updating, plz share the command that you are running.
