### ISSUE TITLE
Working in google colab

### ISSUE THREAD

**Issue by sunny-Ne5** [yaserkl/RLSeq2Seq#33]
WARNING: Logging before flag parsing goes to stderr.
W0624 19:29:10.819931 140309927061376 deprecation_wrapper.py:118] From src/run_summarization.py:795: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

W0624 19:29:10.821898 140309927061376 deprecation_wrapper.py:118] From src/run_summarization.py:661: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

W0624 19:29:10.822178 140309927061376 deprecation_wrapper.py:118] From src/run_summarization.py:661: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

W0624 19:29:10.822366 140309927061376 deprecation_wrapper.py:118] From src/run_summarization.py:662: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.

I0624 19:29:10.822748 140309927061376 run_summarization.py:662] Starting seq2seq_attention in train mode...
Traceback (most recent call last):
  File "src/run_summarization.py", line 795, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "src/run_summarization.py", line 792, in main
    seq2seq.main(unused_argv)
  **File "src/run_summarization.py", line 678, in main
    self.vocab = Vocab(FLAGS.vocab_path, FLAGS.vocab_size) # create a vocabulary
  File "/content/RLSeq2Seq/src/data.py", line 60, in __init__
    with open(vocab_file, 'r') as vocab_f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/data/cnn_dm/finished_files/vocab'**

This is the error I am facing

**Comment by Santosh-Gupta** [comment]
I would like to see a link to your notebook
